name: Checker
on:
  push:
    branches: [ master ]
jobs:
  check_pycodestyle:
    name: check_pycodestyle
    runs-on: python:latest
    steps:
      - pip install pycodestyle
      - pycodestyle Context1.py
      - pycodestyle Context2.py
      - pycodestyle Context3.py
      - pycodestyle Context4.py
      - pycodestyle Context5.py
      - pycodestyle Context6.py
      - pycodestyle Context8.py
  unit-tests:
    name: Unit tests
    runs-on: python:latest
    steps:
      - python -m unittest -v test_case6.py